version: "2"
services:
  frontend:
    environment:
      - NODE_ENV=production
    command: "/bin/bash -c 'yarn install && yarn build && yarn start'"
    restart: always
  gitea:
    restart: always
  postgres:
    restart: always
  nginx:
    environment:
      - "RUN_CERTBOT=true"
      - CERTBOT_DOMAINS=${KITSPACE_DOMAIN},gitea.${KITSPACE_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - /etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
