version: "2"
services:
  nginx:
    environment:
      - RUN_CERTBOT=${RUN_CERTBOT}
      - CERTBOT_DOMAINS=${KITSPACE_DOMAIN},gitea.${KITSPACE_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    volumes:
      - /etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  frontend:
    environment:
      - NODE_ENV=production
    command: "/bin/bash -c 'yarn install && yarn build && yarn start'"
